import { BIZ } from './biz/index.js';
// 銷售網頁可切換的示範商家（全部為虛構，用來展示 GreenUP 適用各種一人公司）
// 阿美手作甜點的商品沿用 data.js 的 PRODUCTS（後台所有資料以阿美為準）
// 其他商家的商品：name 中英、unit、price、cost、stock、desc、art（插圖類型與配色，由銷售網頁繪製）
export const MERCHANTS = [
  {
    id: 'amei', name: '阿美手作甜點', en: "Amei's Handmade Desserts", type: 'dessert', typeName: '手作甜點', owner: '阿美',
    theme: 'cream', tagline: '每一口都是今天現做的', usesStore: true, products: null,
  },
  {
    id: 'coffee', name: '山嵐單人咖啡', en: 'Sanlan Solo Coffee', type: 'coffee', typeName: '精品咖啡烘焙', owner: '阿嵐',
    theme: 'roast', tagline: '一個人烘豆，一次只烘一鍋',
    products: [
      { id: 'cf-yirga', name: '衣索比亞 耶加雪菲', en: 'Ethiopia Yirgacheffe', unit: '半磅', price: 520, cost: 210, stock: 26, desc: '柑橘與茉莉花香，淺焙明亮。', descEn: 'Citrus and jasmine, bright light roast.', art: { kind: 'bag', color: '#E8C07D', accent: '#6B3E26' } },
      { id: 'cf-colombia', name: '哥倫比亞 慧蘭', en: 'Colombia Huila', unit: '半磅', price: 460, cost: 180, stock: 31, desc: '焦糖、堅果，中焙順口。', descEn: 'Caramel and nuts, smooth medium roast.', art: { kind: 'bag', color: '#C98B5B', accent: '#3E2418' } },
      { id: 'cf-house', name: '招牌配方豆', en: 'House Blend', unit: '1 磅', price: 780, cost: 300, stock: 18, desc: '可可與黑糖，做拿鐵也好喝。', descEn: 'Cocoa and brown sugar, great for lattes.', art: { kind: 'bag', color: '#7A4B2F', accent: '#F2D3A0' } },
      { id: 'cf-drip', name: '掛耳包 10 入', en: 'Drip Bags ×10', unit: '10 入', price: 350, cost: 120, stock: 54, desc: '三種單品綜合，上班族最愛。', descEn: 'Three single origins, office favourite.', art: { kind: 'drip', color: '#F4E6CF', accent: '#8C5A3C' } },
      { id: 'cf-cold', name: '冷萃咖啡瓶', en: 'Cold Brew Bottle', unit: '500ml', price: 220, cost: 70, stock: 22, desc: '18 小時低溫萃取，冷藏 5 天。', descEn: '18-hour cold extraction, keeps 5 days chilled.', art: { kind: 'bottle', color: '#3B2416', accent: '#E8C07D' } },
      { id: 'cf-kit', name: '手沖入門組', en: 'Pour-over Starter Kit', unit: '1 組', price: 1680, cost: 900, stock: 8, desc: '濾杯、手沖壺、濾紙與 2 包豆子。', descEn: 'Dripper, kettle, filters and 2 bags of beans.', art: { kind: 'kettle', color: '#D9D4CC', accent: '#3E2418' } },
    ],
  },
  {
    id: 'leather', name: '木白手作皮件', en: 'Mubai Leather Studio', type: 'leather', typeName: '手作皮件', owner: '木白',
    theme: 'leather', tagline: '一針一線，陪你用十年',
    products: [
      { id: 'lt-wallet', name: '植鞣短夾', en: 'Veg-tan Short Wallet', unit: '1 個', price: 2280, cost: 820, stock: 9, desc: '義大利植鞣牛皮，越用越有光澤。', descEn: 'Italian veg-tan leather that patinas beautifully.', art: { kind: 'wallet', color: '#A0612E', accent: '#5A3418' } },
      { id: 'lt-card', name: '名片夾', en: 'Card Holder', unit: '1 個', price: 980, cost: 320, stock: 21, desc: '可刻字，送禮首選。', descEn: 'Engravable, a great gift.', art: { kind: 'card', color: '#C68B59', accent: '#4A2A14' } },
      { id: 'lt-key', name: '皮革鑰匙圈', en: 'Leather Key Ring', unit: '1 個', price: 380, cost: 110, stock: 46, desc: '六色可選，加購刻字。', descEn: 'Six colours, engraving available.', art: { kind: 'key', color: '#7D8C5A', accent: '#3E2E1A' } },
      { id: 'lt-tote', name: '手縫托特包', en: 'Hand-stitched Tote', unit: '1 個', price: 5800, cost: 2400, stock: 4, desc: '全手縫，A4 可放，接單製作 14 天。', descEn: 'Fully hand-stitched, fits A4, made to order in 14 days.', art: { kind: 'tote', color: '#8B5A34', accent: '#E9D3B4' } },
      { id: 'lt-phone', name: '手機斜背包', en: 'Phone Crossbody', unit: '1 個', price: 1680, cost: 620, stock: 12, desc: '輕巧斜背，卡片也放得下。', descEn: 'Light crossbody with card slots.', art: { kind: 'pouch', color: '#B5674D', accent: '#3E2418' } },
      { id: 'lt-oil', name: '皮革保養油', en: 'Leather Care Oil', unit: '50ml', price: 320, cost: 90, stock: 33, desc: '天然蜂蠟配方。', descEn: 'Natural beeswax formula.', art: { kind: 'bottle', color: '#D9A441', accent: '#5A3418' } },
    ],
  },
  {
    id: 'flower', name: '小日子花藝', en: 'Little Days Florist', type: 'flower', typeName: '花藝設計', owner: '小日',
    theme: 'bloom', tagline: '把今天的心情，包成一束花',
    products: [
      { id: 'fl-s', name: '季節花束 S', en: 'Seasonal Bouquet S', unit: '1 束', price: 880, cost: 360, stock: 12, desc: '當季花材，每束都不一樣。', descEn: 'Seasonal stems, every bouquet is unique.', art: { kind: 'bouquet', color: '#F2A7B8', accent: '#6FA36B' } },
      { id: 'fl-m', name: '季節花束 M', en: 'Seasonal Bouquet M', unit: '1 束', price: 1480, cost: 620, stock: 8, desc: '生日、紀念日首選。', descEn: 'Perfect for birthdays and anniversaries.', art: { kind: 'bouquet', color: '#E86F8B', accent: '#5C8E57' } },
      { id: 'fl-dry', name: '乾燥花圈', en: 'Dried Flower Wreath', unit: '1 個', price: 1280, cost: 480, stock: 10, desc: '可保存一年以上。', descEn: 'Lasts over a year.', art: { kind: 'wreath', color: '#D9B48F', accent: '#8A9A5B' } },
      { id: 'fl-pot', name: '療癒小盆栽', en: 'Mini Potted Plant', unit: '1 盆', price: 420, cost: 150, stock: 25, desc: '好照顧，辦公桌最適合。', descEn: 'Easy care, perfect for desks.', art: { kind: 'pot', color: '#7FB77E', accent: '#C9845B' } },
      { id: 'fl-sub', name: '每月花訂閱', en: 'Monthly Flower Subscription', unit: '1 個月', price: 1980, cost: 900, stock: 30, desc: '每週送一束，可暫停。', descEn: 'A bouquet every week, pause anytime.', art: { kind: 'bouquet', color: '#B79AD9', accent: '#6FA36B' } },
      { id: 'fl-open', name: '開幕花籃', en: 'Grand Opening Basket', unit: '1 組', price: 3600, cost: 1500, stock: 5, desc: '台北市區免運，可寫賀卡。', descEn: 'Free delivery in Taipei, card included.', art: { kind: 'basket', color: '#F0A531', accent: '#E86F8B' } },
    ],
  },
  {
    id: 'nail', name: '指尖美甲工作室', en: 'Fingertip Nail Studio', type: 'service', typeName: '美甲預約服務', owner: '小指',
    theme: 'blush', tagline: '一對一服務，不用等',
    products: [
      { id: 'nl-gel', name: '單色凝膠', en: 'Solid Gel', unit: '1 次', price: 900, cost: 220, stock: 20, desc: '約 60 分鐘，含基礎修型。', descEn: 'About 60 minutes, basic shaping included.', art: { kind: 'nail', color: '#E86F8B', accent: '#F7D6DE' } },
      { id: 'nl-french', name: '法式凝膠', en: 'French Gel', unit: '1 次', price: 1200, cost: 260, stock: 16, desc: '約 80 分鐘，經典不退流行。', descEn: 'About 80 minutes, a timeless classic.', art: { kind: 'nail', color: '#F7E7E1', accent: '#C9845B' } },
      { id: 'nl-care', name: '手足保養', en: 'Hand & Foot Care', unit: '1 次', price: 1500, cost: 300, stock: 10, desc: '去角質、保濕、按摩。', descEn: 'Exfoliation, moisturising and massage.', art: { kind: 'lotion', color: '#BFD8C9', accent: '#5C8E57' } },
      { id: 'nl-remove', name: '卸甲', en: 'Gel Removal', unit: '1 次', price: 300, cost: 40, stock: 30, desc: '溫和卸除不傷甲。', descEn: 'Gentle removal, no damage.', art: { kind: 'nail', color: '#D9D4CC', accent: '#8A8A8A' } },
      { id: 'nl-ext', name: '光療延甲', en: 'Gel Extensions', unit: '1 次', price: 2200, cost: 450, stock: 8, desc: '約 120 分鐘，可加購彩繪。', descEn: 'About 120 minutes, nail art available.', art: { kind: 'nail', color: '#B79AD9', accent: '#7C62E6' } },
      { id: 'nl-gift', name: '美甲禮券', en: 'Gift Voucher', unit: '1 張', price: 1000, cost: 0, stock: 99, desc: '一年內有效，可轉贈。', descEn: 'Valid one year, transferable.', art: { kind: 'voucher', color: '#F0A531', accent: '#E86F8B' } },
    ],
  },
  {
    id: 'pho', name: '阿玲越南河粉', en: "Linh's Pho Kitchen", type: 'food', typeName: '越南小吃外帶', owner: '阿玲',
    theme: 'herb', tagline: '媽媽的湯頭，熬足十二小時',
    products: [
      { id: 'ph-beef', name: '生牛肉河粉', en: 'Rare Beef Pho', unit: '1 碗', price: 160, cost: 60, stock: 40, desc: '牛骨熬煮 12 小時，附香草。', descEn: '12-hour beef bone broth with fresh herbs.', art: { kind: 'bowl', color: '#E9C46A', accent: '#C0392B' } },
      { id: 'ph-chicken', name: '雞肉河粉', en: 'Chicken Pho', unit: '1 碗', price: 140, cost: 50, stock: 40, desc: '清爽雞湯，小朋友也愛。', descEn: 'Light chicken broth, kids love it.', art: { kind: 'bowl', color: '#F4E3B1', accent: '#6FA36B' } },
      { id: 'ph-banhmi', name: '越式法國麵包', en: 'Bánh Mì', unit: '1 個', price: 110, cost: 40, stock: 30, desc: '烤豬肉、醃蘿蔔、香菜。', descEn: 'Grilled pork, pickled radish and coriander.', art: { kind: 'baguette', color: '#D99A4E', accent: '#6FA36B' } },
      { id: 'ph-roll', name: '鮮蝦春捲 2 條', en: 'Fresh Shrimp Rolls ×2', unit: '2 條', price: 120, cost: 45, stock: 36, desc: '米紙捲鮮蝦與生菜，附花生醬。', descEn: 'Rice paper rolls with shrimp and greens, peanut dip.', art: { kind: 'roll', color: '#F7D6DE', accent: '#6FA36B' } },
      { id: 'ph-coffee', name: '越南滴漏咖啡', en: 'Vietnamese Drip Coffee', unit: '1 杯', price: 90, cost: 25, stock: 50, desc: '煉乳咖啡，冰熱皆可。', descEn: 'Condensed milk coffee, iced or hot.', art: { kind: 'cup', color: '#5A3418', accent: '#F4E3B1' } },
      { id: 'ph-soup', name: '冷凍湯底包', en: 'Frozen Broth Pack', unit: '1 公升', price: 260, cost: 90, stock: 24, desc: '在家也能煮一鍋，冷凍 3 個月。', descEn: 'Make pho at home, keeps 3 months frozen.', art: { kind: 'pack', color: '#C0392B', accent: '#E9C46A' } },
    ],
  },
];
export const MERCHANT_MAP = {}; // 於檔尾建立（含 50 種業態）

// ── 追加欄位（銷售網頁多語與風格用；不更動上方既有欄位）──────────────────────────
// brand：logo 色塊；layout：前台版面（每個業主不同）；ship：運送模式與運費；copy：前台文案（中英日越馬）
// 商品：i18n { en|ja|vi|ms: [名稱, 單位, 描述] }、tags（標籤）、kw（AI 導購辨識關鍵字）
const EXTRA = {
  amei: { cat: 'dessert', brand: '#F7B2C4', layout: 'classic', ship: { mode: 'ship', fee: 150, free: 1500 } },
  coffee: {
    cat: 'drink', brand: '#6B3E26', layout: 'editorial', ship: { mode: 'ship', fee: 150, free: 1500 },
    copy: {
      zh: { type: '精品咖啡烘焙', tagline: '一個人烘豆，一次只烘一鍋', kicker: 'VOL.07 ・ 本週烘焙日誌', title: '一個人烘豆，<br>一次只烘一鍋。', sub: '阿嵐每週二、五親手烘豆，烘好 48 小時內出貨。不知道選淺焙還是深焙？右下角的 AI 導購會依你的口味推薦。', prodTitle: '本週烘焙', prodSub: '每支豆子都有杯測筆記，少量烘焙、新鮮直送', about: '關於阿嵐', f: [['新鮮烘焙', '烘好 48 小時內出貨'], ['常溫宅配', '滿 NT$1,500 免運'], ['多語言 AI 導購', '中・英・日・越・馬來文']], chips: ['推薦入門豆', '送禮選什麼？', '預算 500 元', '運費怎麼算？', '有掛耳包嗎？', '結帳'] },
      en: { type: 'Specialty coffee roaster', tagline: 'One roaster, one small batch at a time', kicker: 'VOL.07 · This week’s roast journal', title: 'One roaster.<br>One small batch.', sub: 'Lan roasts by hand every Tuesday and Friday and ships within 48 hours. Light or dark? Our AI concierge (bottom right) will match your taste.', prodTitle: 'This week’s roast', prodSub: 'Every coffee comes with cupping notes. Small batches, shipped fresh', about: 'About Lan', f: [['Freshly roasted', 'Ships within 48 hours'], ['Home delivery', 'Free over NT$1,500'], ['Multilingual AI help', '中 · EN · 日 · VI · MS']], chips: ['Best beans for beginners', 'Gift ideas?', 'Budget NT$500', 'How much is shipping?', 'Any drip bags?', 'Checkout'] },
      ja: { type: 'スペシャルティコーヒー焙煎所', tagline: 'ひとりで焙煎、一度にひと釜だけ', kicker: 'VOL.07 ・ 今週の焙煎日誌', title: 'ひとりで焙煎、<br>ひと釜ずつ丁寧に。', sub: 'ランが毎週火・金に手焙煎し、48時間以内に発送します。浅煎りか深煎りか迷ったら、右下のAIスタッフにご相談ください。', prodTitle: '今週の焙煎', prodSub: 'すべての豆にカッピングノート付き。少量焙煎で新鮮にお届け', about: 'ランについて', f: [['焙煎したて', '焙煎後48時間以内に発送'], ['常温配送', 'NT$1,500以上で送料無料'], ['多言語AI対応', '中・英・日・越・マレー語']], chips: ['初心者におすすめの豆', 'ギフトは何がいい？', '予算500元', '送料はいくら？', 'ドリップバッグある？', 'お会計'] },
      vi: { type: 'Rang xay cà phê đặc sản', tagline: 'Một người rang, mỗi lần một mẻ nhỏ', kicker: 'VOL.07 · Nhật ký rang tuần này', title: 'Một người rang,<br>từng mẻ nhỏ.', sub: 'Lan tự tay rang vào thứ Ba và thứ Sáu, giao trong 48 giờ. Phân vân rang nhạt hay rang đậm? Trợ lý AI (góc dưới bên phải) sẽ gợi ý theo khẩu vị của bạn.', prodTitle: 'Mẻ rang tuần này', prodSub: 'Mỗi loại đều có ghi chú nếm thử. Rang mẻ nhỏ, giao tươi', about: 'Về Lan', f: [['Rang tươi', 'Giao trong 48 giờ'], ['Giao tận nhà', 'Miễn phí từ NT$1,500'], ['AI đa ngôn ngữ', 'Trung · Anh · Nhật · Việt · Mã Lai']], chips: ['Gợi ý hạt cho người mới', 'Nên tặng quà gì?', 'Ngân sách 500', 'Phí giao hàng?', 'Có túi lọc không?', 'Thanh toán'] },
      ms: { type: 'Pemanggang kopi istimewa', tagline: 'Seorang pemanggang, satu kelompok kecil', kicker: 'VOL.07 · Jurnal panggang minggu ini', title: 'Seorang pemanggang,<br>satu kelompok kecil.', sub: 'Lan memanggang sendiri setiap Selasa dan Jumaat, dihantar dalam 48 jam. Panggang cerah atau gelap? Pembantu AI (bawah kanan) akan bantu ikut citarasa anda.', prodTitle: 'Panggangan minggu ini', prodSub: 'Setiap kopi ada nota rasa. Kelompok kecil, dihantar segar', about: 'Tentang Lan', f: [['Baru dipanggang', 'Dihantar dalam 48 jam'], ['Penghantaran ke rumah', 'Percuma melebihi NT$1,500'], ['AI pelbagai bahasa', 'Cina · EN · Jepun · VI · MS']], chips: ['Biji kopi untuk pemula', 'Idea hadiah?', 'Bajet NT$500', 'Kos penghantaran?', 'Ada beg titis?', 'Bayar'] },
    },
    products: {
      'cf-yirga': { tags: ['hot', 'light'], kw: ['耶加', '雪菲', '衣索比亞', '淺焙', '果酸', '入門', 'ethiopia', 'yirga', 'light roast', 'beginner', 'エチオピア', '浅煎り'], i18n: { en: ['Ethiopia Yirgacheffe', 'Half lb', 'Citrus and jasmine, bright light roast.'], ja: ['エチオピア イルガチェフェ', '半ポンド', '柑橘とジャスミンの香り、明るい浅煎り。'], vi: ['Ethiopia Yirgacheffe', 'Nửa pound', 'Hương cam chanh và hoa nhài, rang nhạt tươi sáng.'], ms: ['Ethiopia Yirgacheffe', 'Separuh paun', 'Sitrus dan melati, panggang cerah.'] } },
      'cf-colombia': { tags: ['hot'], kw: ['哥倫比亞', '慧蘭', '中焙', '焦糖', 'colombia', 'huila', 'medium', 'コロンビア'], i18n: { en: ['Colombia Huila', 'Half lb', 'Caramel and nuts, smooth medium roast.'], ja: ['コロンビア ウイラ', '半ポンド', 'キャラメルとナッツ、なめらかな中煎り。'], vi: ['Colombia Huila', 'Nửa pound', 'Vị caramel và hạt, rang vừa êm.'], ms: ['Colombia Huila', 'Separuh paun', 'Karamel dan kacang, panggang sederhana yang lembut.'] } },
      'cf-house': { tags: ['gift', 'value'], kw: ['配方', '招牌', '拿鐵', '深焙', 'blend', 'house', 'latte', 'dark', 'ブレンド', 'ラテ'], i18n: { en: ['House Blend', '1 lb', 'Cocoa and brown sugar, great for lattes.'], ja: ['ハウスブレンド', '1ポンド', 'カカオと黒糖、ラテにもぴったり。'], vi: ['Cà phê pha trộn đặc trưng', '1 pound', 'Vị cacao và đường nâu, pha latte rất ngon.'], ms: ['Adunan Rumah', '1 paun', 'Koko dan gula perang, sesuai untuk latte.'] } },
      'cf-drip': { tags: ['hot', 'gift'], kw: ['掛耳', '濾掛', '上班', '方便', 'drip', 'drip bag', 'office', 'ドリップ', 'túi lọc', 'beg titis'], i18n: { en: ['Drip Bags ×10', '10 bags', 'Three single origins, an office favourite.'], ja: ['ドリップバッグ 10袋', '10袋', '3種のシングルオリジン、オフィスで人気。'], vi: ['Túi lọc cà phê ×10', '10 túi', 'Ba loại hạt đơn, dân văn phòng rất thích.'], ms: ['Beg Kopi Titis ×10', '10 beg', 'Tiga asal tunggal, kegemaran pejabat.'] } },
      'cf-cold': { tags: ['new'], kw: ['冷萃', '冰', 'cold brew', 'cold', 'iced', '水出し', 'コールドブリュー'], i18n: { en: ['Cold Brew Bottle', '500ml', '18-hour cold extraction, keeps 5 days chilled.'], ja: ['コールドブリュー', '500ml', '18時間かけて低温抽出、冷蔵で5日保存。'], vi: ['Cà phê ủ lạnh', '500ml', 'Ủ lạnh 18 giờ, bảo quản lạnh 5 ngày.'], ms: ['Kopi Bancuh Sejuk', '500ml', 'Pengekstrakan sejuk 18 jam, tahan 5 hari dalam peti sejuk.'] } },
      'cf-kit': { tags: ['gift', 'starter'], kw: ['手沖', '器材', '入門組', '濾杯', '手沖壺', 'kit', 'pour-over', 'kettle', 'ハンドドリップ', 'セット'], i18n: { en: ['Pour-over Starter Kit', '1 set', 'Dripper, kettle, filters and 2 bags of beans.'], ja: ['ハンドドリップ入門セット', '1セット', 'ドリッパー、ケトル、フィルター、豆2袋入り。'], vi: ['Bộ pha thủ công cho người mới', '1 bộ', 'Phễu lọc, ấm rót, giấy lọc và 2 túi hạt.'], ms: ['Set Permulaan Pour-over', '1 set', 'Penitis, cerek, penapis dan 2 beg biji kopi.'] } },
    },
  },
  leather: {
    cat: 'craft', brand: '#8B5A34', layout: 'atelier', ship: { mode: 'ship', fee: 150, free: 1500 },
    copy: {
      zh: { type: '手作皮件', tagline: '一針一線，陪你用十年', kicker: 'HANDMADE IN TAINAN', title: '一針一線，<br>陪你用十年。', sub: '木白在台南老屋裡一個人裁皮、手縫、封邊。每件皮件都能免費刻字，AI 導購會幫你挑適合送禮的款式。', prodTitle: '工作室作品', prodSub: '義大利植鞣牛皮，全手工縫製，越用越有光澤', about: '關於木白', f: [['全手工縫製', '每件都有職人編號'], ['免費刻字', '送禮附禮盒與防塵袋'], ['多語言 AI 導購', '中・英・日・越・馬來文']], chips: ['推薦入門款', '送禮選什麼？', '預算 1000 元', '運費怎麼算？', '可以刻字嗎？', '結帳'] },
      en: { type: 'Handmade leather goods', tagline: 'Stitched by hand to last a decade', kicker: 'HANDMADE IN TAINAN', title: 'Stitched by hand.<br>Made to last.', sub: 'Mubai cuts, stitches and finishes every piece alone in an old Tainan house. Free engraving on everything; our AI concierge helps you pick the perfect gift.', prodTitle: 'From the atelier', prodSub: 'Italian veg-tan leather, fully hand-stitched, ages beautifully', about: 'About Mubai', f: [['Fully hand-stitched', 'Each piece is numbered'], ['Free engraving', 'Gift box and dust bag included'], ['Multilingual AI help', '中 · EN · 日 · VI · MS']], chips: ['A good first piece', 'Gift ideas?', 'Budget NT$1,000', 'How much is shipping?', 'Can you engrave?', 'Checkout'] },
      ja: { type: '手作り革小物', tagline: 'ひと針ずつ、十年使えるものを', kicker: 'HANDMADE IN TAINAN', title: 'ひと針ずつ、<br>十年寄り添う革小物。', sub: 'ムーバイが台南の古民家でひとり裁断・手縫い・コバ仕上げをしています。名入れ無料、ギフト選びはAIスタッフにご相談ください。', prodTitle: 'アトリエの作品', prodSub: 'イタリアンベジタブルタンニンレザー、すべて手縫い', about: 'ムーバイについて', f: [['すべて手縫い', '一点ずつ職人番号入り'], ['名入れ無料', 'ギフトボックスと保存袋付き'], ['多言語AI対応', '中・英・日・越・マレー語']], chips: ['最初のひとつにおすすめ', 'ギフトは何がいい？', '予算1000元', '送料はいくら？', '名入れできる？', 'お会計'] },
      vi: { type: 'Đồ da thủ công', tagline: 'Từng mũi khâu, dùng cả chục năm', kicker: 'HANDMADE IN TAINAN', title: 'Từng mũi khâu tay,<br>bền bỉ mười năm.', sub: 'Mubai một mình cắt da, khâu tay và hoàn thiện trong căn nhà cổ ở Đài Nam. Khắc tên miễn phí; trợ lý AI giúp bạn chọn quà phù hợp.', prodTitle: 'Tác phẩm của xưởng', prodSub: 'Da thuộc thảo mộc Ý, khâu tay hoàn toàn, càng dùng càng bóng đẹp', about: 'Về Mubai', f: [['Khâu tay hoàn toàn', 'Mỗi món đều có số hiệu'], ['Khắc tên miễn phí', 'Kèm hộp quà và túi chống bụi'], ['AI đa ngôn ngữ', 'Trung · Anh · Nhật · Việt · Mã Lai']], chips: ['Món nên mua đầu tiên', 'Nên tặng quà gì?', 'Ngân sách 1000', 'Phí giao hàng?', 'Có khắc tên không?', 'Thanh toán'] },
      ms: { type: 'Barangan kulit buatan tangan', tagline: 'Dijahit tangan untuk sedekad', kicker: 'HANDMADE IN TAINAN', title: 'Dijahit tangan,<br>tahan sedekad.', sub: 'Mubai memotong, menjahit dan menyiapkan setiap barang seorang diri di rumah lama Tainan. Ukiran nama percuma; pembantu AI bantu pilih hadiah.', prodTitle: 'Dari bengkel', prodSub: 'Kulit samak sayuran Itali, dijahit tangan sepenuhnya', about: 'Tentang Mubai', f: [['Dijahit tangan', 'Setiap barang bernombor'], ['Ukiran percuma', 'Kotak hadiah dan beg habuk'], ['AI pelbagai bahasa', 'Cina · EN · Jepun · VI · MS']], chips: ['Pilihan pertama terbaik', 'Idea hadiah?', 'Bajet NT$1,000', 'Kos penghantaran?', 'Boleh ukir nama?', 'Bayar'] },
    },
    products: {
      'lt-wallet': { tags: ['hot', 'gift'], kw: ['短夾', '皮夾', '錢包', 'wallet', '財布', 'ví'], i18n: { en: ['Veg-tan Short Wallet', '1 pc', 'Italian veg-tan leather that patinas beautifully.'], ja: ['ヌメ革ショートウォレット', '1個', 'イタリアンヌメ革、使うほどに艶が増します。'], vi: ['Ví ngắn da thảo mộc', '1 cái', 'Da thuộc thảo mộc Ý, càng dùng càng bóng đẹp.'], ms: ['Dompet Pendek Kulit', '1 unit', 'Kulit samak sayuran Itali yang semakin berkilat.'] } },
      'lt-card': { tags: ['gift', 'starter'], kw: ['名片', '卡夾', 'card', 'card holder', '名刺', 'thẻ', 'kad'], i18n: { en: ['Card Holder', '1 pc', 'Engravable, a great gift.'], ja: ['名刺入れ', '1個', '名入れ可能、贈り物に最適。'], vi: ['Ví đựng danh thiếp', '1 cái', 'Có thể khắc tên, rất hợp làm quà.'], ms: ['Pemegang Kad', '1 unit', 'Boleh diukir, hadiah yang hebat.'] } },
      'lt-key': { tags: ['starter', 'value'], kw: ['鑰匙', 'key', 'キーリング', 'chìa khóa', 'kunci'], i18n: { en: ['Leather Key Ring', '1 pc', 'Six colours, engraving available.'], ja: ['レザーキーリング', '1個', '6色から選べて名入れも可能。'], vi: ['Móc khóa da', '1 cái', 'Sáu màu, có thể khắc tên.'], ms: ['Gantungan Kunci Kulit', '1 unit', 'Enam warna, boleh diukir.'] } },
      'lt-tote': { tags: ['limited'], kw: ['托特', '包包', '大包', 'tote', 'bag', 'トート', 'túi', 'beg'], i18n: { en: ['Hand-stitched Tote', '1 pc', 'Fully hand-stitched, fits A4, made to order in 14 days.'], ja: ['手縫いトートバッグ', '1個', 'すべて手縫い、A4対応、受注製作14日。'], vi: ['Túi tote khâu tay', '1 cái', 'Khâu tay hoàn toàn, vừa A4, đặt làm 14 ngày.'], ms: ['Beg Tote Jahitan Tangan', '1 unit', 'Dijahit tangan, muat A4, ditempah dalam 14 hari.'] } },
      'lt-phone': { tags: ['new'], kw: ['手機', '斜背', 'phone', 'crossbody', 'スマホ', 'điện thoại', 'telefon'], i18n: { en: ['Phone Crossbody', '1 pc', 'Light crossbody with card slots.'], ja: ['スマホショルダー', '1個', 'カードも入る軽量ショルダー。'], vi: ['Túi đeo chéo điện thoại', '1 cái', 'Túi đeo chéo nhẹ, có ngăn thẻ.'], ms: ['Beg Silang Telefon', '1 unit', 'Beg silang ringan dengan slot kad.'] } },
      'lt-oil': { tags: ['value'], kw: ['保養', '油', 'oil', 'care', 'オイル', 'dầu', 'minyak'], i18n: { en: ['Leather Care Oil', '50ml', 'Natural beeswax formula.'], ja: ['レザーケアオイル', '50ml', '天然ミツロウ配合。'], vi: ['Dầu dưỡng da', '50ml', 'Công thức sáp ong tự nhiên.'], ms: ['Minyak Penjagaan Kulit', '50ml', 'Formula lilin lebah semula jadi.'] } },
    },
  },
  flower: {
    cat: 'flower', brand: '#E86F8B', layout: 'soft', ship: { mode: 'ship', fee: 150, free: 1500 },
    copy: {
      zh: { type: '花藝設計', tagline: '把今天的心情，包成一束花', kicker: '每週一、四 花市直送', title: '把今天的心情，<br>包成一束花。', sub: '小日每週到花市挑最新鮮的花材，一束一束親手包。生日、紀念日、開幕賀禮，告訴 AI 導購預算和對象，它會幫你挑。', prodTitle: '本週花禮', prodSub: '當季花材，每一束都是獨一無二', about: '關於小日', f: [['當日鮮花', '每週兩次花市直送'], ['雙北冷藏配送', '滿 NT$1,500 免運'], ['多語言 AI 導購', '中・英・日・越・馬來文']], chips: ['推薦人氣花束', '送女友選什麼？', '預算 1000 元', '運費怎麼算？', '有開幕花籃嗎？', '結帳'] },
      en: { type: 'Floral design', tagline: 'Today’s mood, wrapped as flowers', kicker: 'Fresh from the market every Mon & Thu', title: 'Today’s mood,<br>wrapped in flowers.', sub: 'Xiaori picks the freshest stems at the flower market twice a week and wraps every bouquet by hand. Tell our AI concierge your budget and who it’s for.', prodTitle: 'This week’s flowers', prodSub: 'Seasonal stems, every bouquet is one of a kind', about: 'About Xiaori', f: [['Fresh daily', 'Market-fresh twice a week'], ['Chilled delivery', 'Free over NT$1,500'], ['Multilingual AI help', '中 · EN · 日 · VI · MS']], chips: ['Popular bouquets', 'Gift for my partner?', 'Budget NT$1,000', 'How much is shipping?', 'Opening baskets?', 'Checkout'] },
      ja: { type: 'フラワーデザイン', tagline: '今日の気持ちを、花束に', kicker: '毎週月・木 市場から直送', title: '今日の気持ちを、<br>花束にして。', sub: 'シャオリーが週2回市場で新鮮な花を選び、一束ずつ手作りしています。ご予算と贈る相手をAIスタッフに伝えれば、ぴったりの花をご提案します。', prodTitle: '今週のお花', prodSub: '季節の花材で、どれも一点もの', about: 'シャオリーについて', f: [['当日の生花', '週2回市場から直送'], ['冷蔵配送', 'NT$1,500以上で送料無料'], ['多言語AI対応', '中・英・日・越・マレー語']], chips: ['人気の花束', '恋人へのギフトは？', '予算1000元', '送料はいくら？', '開店祝いの花は？', 'お会計'] },
      vi: { type: 'Thiết kế hoa', tagline: 'Gói tâm trạng hôm nay thành bó hoa', kicker: 'Hoa tươi từ chợ mỗi thứ Hai & Năm', title: 'Gói tâm trạng hôm nay<br>thành một bó hoa.', sub: 'Xiaori chọn hoa tươi nhất ở chợ hoa hai lần mỗi tuần và tự tay gói từng bó. Hãy cho trợ lý AI biết ngân sách và người nhận nhé.', prodTitle: 'Hoa tuần này', prodSub: 'Hoa theo mùa, mỗi bó đều độc nhất', about: 'Về Xiaori', f: [['Hoa tươi mỗi ngày', 'Nhập chợ hai lần/tuần'], ['Giao hàng lạnh', 'Miễn phí từ NT$1,500'], ['AI đa ngôn ngữ', 'Trung · Anh · Nhật · Việt · Mã Lai']], chips: ['Bó hoa được yêu thích', 'Tặng bạn gái chọn gì?', 'Ngân sách 1000', 'Phí giao hàng?', 'Có lẵng hoa khai trương?', 'Thanh toán'] },
      ms: { type: 'Rekaan bunga', tagline: 'Perasaan hari ini, dalam sejambak bunga', kicker: 'Segar dari pasar setiap Isnin & Khamis', title: 'Perasaan hari ini,<br>dalam sejambak bunga.', sub: 'Xiaori memilih bunga paling segar di pasar dua kali seminggu dan membalut setiap jambak sendiri. Beritahu pembantu AI bajet dan penerimanya.', prodTitle: 'Bunga minggu ini', prodSub: 'Bunga bermusim, setiap jambak unik', about: 'Tentang Xiaori', f: [['Segar setiap hari', 'Dari pasar dua kali seminggu'], ['Penghantaran sejuk', 'Percuma melebihi NT$1,500'], ['AI pelbagai bahasa', 'Cina · EN · Jepun · VI · MS']], chips: ['Jambak popular', 'Hadiah untuk pasangan?', 'Bajet NT$1,000', 'Kos penghantaran?', 'Bakul pembukaan?', 'Bayar'] },
    },
    products: {
      'fl-s': { tags: ['hot', 'starter'], kw: ['花束', '小束', 'bouquet', 'small', '花束', 'bó hoa', 'jambak'], i18n: { en: ['Seasonal Bouquet S', '1 bunch', 'Seasonal stems, every bouquet is unique.'], ja: ['季節の花束 S', '1束', '季節の花材で、ひとつひとつ違う花束。'], vi: ['Bó hoa theo mùa S', '1 bó', 'Hoa theo mùa, mỗi bó một vẻ.'], ms: ['Jambak Bermusim S', '1 jambak', 'Bunga bermusim, setiap jambak unik.'] } },
      'fl-m': { tags: ['hot', 'gift'], kw: ['生日', '紀念日', '女友', '情人', 'birthday', 'anniversary', 'partner', '誕生日', '記念日', 'sinh nhật', 'hari jadi'], i18n: { en: ['Seasonal Bouquet M', '1 bunch', 'Perfect for birthdays and anniversaries.'], ja: ['季節の花束 M', '1束', '誕生日や記念日にぴったり。'], vi: ['Bó hoa theo mùa M', '1 bó', 'Hoàn hảo cho sinh nhật và kỷ niệm.'], ms: ['Jambak Bermusim M', '1 jambak', 'Sesuai untuk hari jadi dan ulang tahun.'] } },
      'fl-dry': { tags: ['gift'], kw: ['乾燥', '花圈', 'dried', 'wreath', 'ドライ', 'リース', 'hoa khô', 'kering'], i18n: { en: ['Dried Flower Wreath', '1 pc', 'Lasts over a year.'], ja: ['ドライフラワーリース', '1個', '1年以上楽しめます。'], vi: ['Vòng hoa khô', '1 cái', 'Giữ được hơn một năm.'], ms: ['Kalungan Bunga Kering', '1 unit', 'Tahan lebih setahun.'] } },
      'fl-pot': { tags: ['value', 'starter'], kw: ['盆栽', '植物', '辦公', 'plant', 'pot', 'desk', '観葉', 'chậu cây', 'pokok'], i18n: { en: ['Mini Potted Plant', '1 pot', 'Easy care, perfect for desks.'], ja: ['ミニ観葉植物', '1鉢', 'お手入れ簡単、デスクに最適。'], vi: ['Chậu cây mini', '1 chậu', 'Dễ chăm, hợp để bàn làm việc.'], ms: ['Pokok Pasu Mini', '1 pasu', 'Mudah dijaga, sesuai di meja.'] } },
      'fl-sub': { tags: ['sub', 'new'], kw: ['訂閱', '每月', '每週', 'subscription', 'monthly', '定期便', 'đăng ký', 'langganan'], i18n: { en: ['Monthly Flower Subscription', '1 month', 'A bouquet every week, pause anytime.'], ja: ['お花の定期便（月額）', '1か月', '毎週花束をお届け、いつでも一時停止可。'], vi: ['Gói hoa hằng tháng', '1 tháng', 'Mỗi tuần một bó, tạm dừng bất cứ lúc nào.'], ms: ['Langganan Bunga Bulanan', '1 bulan', 'Sejambak setiap minggu, boleh berhenti bila-bila.'] } },
      'fl-open': { tags: ['limited'], kw: ['開幕', '花籃', '賀禮', 'opening', 'basket', '開店祝い', 'khai trương', 'pembukaan'], i18n: { en: ['Grand Opening Basket', '1 set', 'Free delivery in Taipei, card included.'], ja: ['開店祝いフラワーバスケット', '1セット', '台北市内配送無料、メッセージカード付き。'], vi: ['Lẵng hoa khai trương', '1 bộ', 'Miễn phí giao trong Đài Bắc, kèm thiệp.'], ms: ['Bakul Bunga Pembukaan', '1 set', 'Penghantaran percuma di Taipei, termasuk kad.'] } },
    },
  },
  nail: {
    cat: 'service', brand: '#C9789A', layout: 'booking', ship: { mode: 'service', fee: 150, free: 1500 },
    copy: {
      zh: { type: '美甲預約服務', tagline: '一對一服務，不用等', kicker: '一對一包廂・完全預約制', title: '一對一服務，<br>指尖的小日子。', sub: '小指一個人經營，每個時段只服務一位客人。直接線上預約付款，AI 導購會用你的語言確認時段與款式。', prodTitle: '服務項目', prodSub: '價格含基礎修型，預約成功後 AI 會傳訊息確認時段', about: '關於小指', f: [['完全預約制', '不用排隊、不會被插隊'], ['線上預付', '可用禮券折抵'], ['多語言 AI 預約', '中・英・日・越・馬來文']], chips: ['推薦人氣款', '我要預約', '預算 1000 元', '可以改時間嗎？', '有禮券嗎？', '結帳'] },
      en: { type: 'Nail salon (by appointment)', tagline: 'One-to-one, no waiting', kicker: 'Private room · Appointment only', title: 'One-to-one care,<br>right at your fingertips.', sub: 'Xiaozhi runs the studio alone and serves one guest per slot. Book and pay online; our AI concierge confirms your time and design in your language.', prodTitle: 'Services', prodSub: 'Basic shaping included. Our AI confirms your slot after booking', about: 'About Xiaozhi', f: [['Appointment only', 'No queues, no double-booking'], ['Prepay online', 'Gift vouchers accepted'], ['Multilingual AI booking', '中 · EN · 日 · VI · MS']], chips: ['Most popular', 'Book a slot', 'Budget NT$1,000', 'Can I reschedule?', 'Gift vouchers?', 'Checkout'] },
      ja: { type: 'ネイルサロン（予約制）', tagline: 'マンツーマンで待ち時間なし', kicker: '個室・完全予約制', title: 'マンツーマンで、<br>指先にご褒美を。', sub: 'シャオジーがひとりで営業し、各時間帯お一人様だけの施術です。オンラインで予約・お支払いいただくと、AIスタッフが日本語で時間とデザインを確認します。', prodTitle: 'メニュー', prodSub: '基本の形整え込み。ご予約後AIが時間を確認します', about: 'シャオジーについて', f: [['完全予約制', '待ち時間なし'], ['オンライン前払い', 'ギフト券も使えます'], ['多言語AI予約', '中・英・日・越・マレー語']], chips: ['人気メニュー', '予約したい', '予算1000元', '予約変更できる？', 'ギフト券ある？', 'お会計'] },
      vi: { type: 'Làm móng (đặt lịch)', tagline: 'Phục vụ riêng, không phải chờ', kicker: 'Phòng riêng · Chỉ nhận đặt lịch', title: 'Phục vụ riêng từng người,<br>chăm chút đầu ngón tay.', sub: 'Xiaozhi tự vận hành tiệm, mỗi khung giờ chỉ phục vụ một khách. Đặt lịch và thanh toán online; trợ lý AI sẽ xác nhận giờ và mẫu bằng tiếng Việt.', prodTitle: 'Dịch vụ', prodSub: 'Đã gồm tạo dáng cơ bản. AI xác nhận khung giờ sau khi đặt', about: 'Về Xiaozhi', f: [['Chỉ nhận đặt lịch', 'Không phải xếp hàng'], ['Thanh toán trước', 'Nhận phiếu quà tặng'], ['AI đặt lịch đa ngôn ngữ', 'Trung · Anh · Nhật · Việt · Mã Lai']], chips: ['Dịch vụ được yêu thích', 'Tôi muốn đặt lịch', 'Ngân sách 1000', 'Đổi giờ được không?', 'Có phiếu quà tặng?', 'Thanh toán'] },
      ms: { type: 'Salon kuku (temujanji)', tagline: 'Satu lawan satu, tanpa menunggu', kicker: 'Bilik peribadi · Temujanji sahaja', title: 'Layanan peribadi,<br>di hujung jari anda.', sub: 'Xiaozhi mengendalikan studio seorang diri, satu pelanggan bagi setiap slot. Tempah dan bayar dalam talian; pembantu AI mengesahkan masa dan reka bentuk dalam bahasa anda.', prodTitle: 'Perkhidmatan', prodSub: 'Termasuk bentuk asas. AI sahkan slot selepas tempahan', about: 'Tentang Xiaozhi', f: [['Temujanji sahaja', 'Tiada barisan'], ['Prabayar dalam talian', 'Baucar hadiah diterima'], ['Tempahan AI pelbagai bahasa', 'Cina · EN · Jepun · VI · MS']], chips: ['Paling popular', 'Saya mahu tempah', 'Bajet NT$1,000', 'Boleh tukar masa?', 'Ada baucar hadiah?', 'Bayar'] },
    },
    products: {
      'nl-gel': { tags: ['hot', 'starter'], dur: 60, kw: ['單色', '凝膠', 'gel', 'solid', 'ワンカラー', 'sơn gel', 'gel kuku'], i18n: { en: ['Solid Gel', '1 session', 'About 60 minutes, basic shaping included.'], ja: ['ワンカラージェル', '1回', '約60分、基本の形整え込み。'], vi: ['Sơn gel một màu', '1 lần', 'Khoảng 60 phút, gồm tạo dáng cơ bản.'], ms: ['Gel Satu Warna', '1 sesi', 'Kira-kira 60 minit, termasuk bentuk asas.'] } },
      'nl-french': { tags: ['hot'], dur: 80, kw: ['法式', 'french', 'フレンチ', 'kiểu pháp', 'perancis'], i18n: { en: ['French Gel', '1 session', 'About 80 minutes, a timeless classic.'], ja: ['フレンチジェル', '1回', '約80分、定番の上品さ。'], vi: ['Gel kiểu Pháp', '1 lần', 'Khoảng 80 phút, cổ điển không lỗi mốt.'], ms: ['Gel Perancis', '1 sesi', 'Kira-kira 80 minit, klasik sepanjang zaman.'] } },
      'nl-care': { tags: ['value'], dur: 70, kw: ['保養', '手足', '去角質', 'care', 'spa', 'hand', 'foot', 'ケア', 'chăm sóc', 'rawatan'], i18n: { en: ['Hand & Foot Care', '1 session', 'Exfoliation, moisturising and massage.'], ja: ['ハンド＆フットケア', '1回', '角質ケア・保湿・マッサージ。'], vi: ['Chăm sóc tay chân', '1 lần', 'Tẩy da chết, dưỡng ẩm và massage.'], ms: ['Rawatan Tangan & Kaki', '1 sesi', 'Pengelupasan, pelembapan dan urutan.'] } },
      'nl-remove': { tags: ['value'], dur: 30, kw: ['卸甲', 'removal', 'remove', 'オフ', 'tháo', 'tanggal'], i18n: { en: ['Gel Removal', '1 session', 'Gentle removal, no damage.'], ja: ['ジェルオフ', '1回', '爪を傷めない丁寧なオフ。'], vi: ['Tháo gel', '1 lần', 'Tháo nhẹ nhàng, không hại móng.'], ms: ['Tanggal Gel', '1 sesi', 'Penanggalan lembut, tanpa kerosakan.'] } },
      'nl-ext': { tags: ['limited'], dur: 120, kw: ['延甲', '光療', '彩繪', 'extension', 'nail art', '長さ出し', 'nối móng', 'sambungan'], i18n: { en: ['Gel Extensions', '1 session', 'About 120 minutes, nail art available.'], ja: ['ジェルスカルプ', '1回', '約120分、アートも追加できます。'], vi: ['Nối móng gel', '1 lần', 'Khoảng 120 phút, có thể vẽ thêm.'], ms: ['Sambungan Gel', '1 sesi', 'Kira-kira 120 minit, seni kuku tersedia.'] } },
      'nl-gift': { tags: ['gift'], kw: ['禮券', '禮物', '送禮', 'voucher', 'gift', 'ギフト券', 'phiếu', 'baucar'], i18n: { en: ['Gift Voucher', '1 voucher', 'Valid one year, transferable.'], ja: ['ネイルギフト券', '1枚', '1年間有効、譲渡可能。'], vi: ['Phiếu quà tặng', '1 phiếu', 'Hiệu lực một năm, có thể chuyển nhượng.'], ms: ['Baucar Hadiah', '1 baucar', 'Sah setahun, boleh dipindah milik.'] } },
    },
  },
  pho: {
    cat: 'food', brand: '#2F7D4F', layout: 'menu', ship: { mode: 'takeout', fee: 150, free: 1500 },
    copy: {
      zh: { type: '越南小吃外帶', tagline: '媽媽的湯頭，熬足十二小時', kicker: '中壢在地・外帶外送', title: '媽媽的湯頭，<br>熬足十二小時。', sub: '阿玲每天清晨熬牛骨湯，香草當天現採。線上點餐、到店自取免排隊，也能外送；看不懂越南菜？AI 導購會用你的語言介紹。', prodTitle: '今日菜單', prodSub: '下單後約 15 分鐘出餐，可選外帶自取或外送', about: '關於阿玲', f: [['現熬湯頭', '每天清晨熬 12 小時'], ['外帶免排隊', '外送滿 NT$1,500 免運'], ['多語言 AI 點餐', '中・英・日・越・馬來文']], chips: ['推薦招牌', '一個人吃什麼？', '預算 300 元', '外送怎麼算？', '有素食嗎？', '結帳'] },
      en: { type: 'Vietnamese takeaway', tagline: 'Mum’s broth, simmered 12 hours', kicker: 'Zhongli local · Takeaway & delivery', title: 'Mum’s broth,<br>simmered for 12 hours.', sub: 'Linh simmers beef bone broth every dawn with herbs picked the same day. Order online, skip the queue or get it delivered. New to Vietnamese food? Our AI concierge explains in your language.', prodTitle: 'Today’s menu', prodSub: 'Ready in about 15 minutes. Pick up or delivery', about: 'About Linh', f: [['Fresh broth', 'Simmered 12 hours every dawn'], ['Skip the queue', 'Free delivery over NT$1,500'], ['Multilingual AI ordering', '中 · EN · 日 · VI · MS']], chips: ['Signature dishes', 'Eating alone?', 'Budget NT$300', 'Delivery fee?', 'Vegetarian options?', 'Checkout'] },
      ja: { type: 'ベトナム料理テイクアウト', tagline: '母の味のスープ、12時間煮込み', kicker: '中壢ローカル・テイクアウト＆デリバリー', title: '母の味のスープ、<br>12時間じっくり煮込み。', sub: 'リンが毎朝牛骨スープを煮込み、ハーブはその日に摘んだもの。オンライン注文で並ばずに受け取れ、デリバリーも可能です。ベトナム料理が初めてでもAIスタッフが日本語でご案内します。', prodTitle: '本日のメニュー', prodSub: 'ご注文から約15分でご用意。持ち帰りまたはデリバリー', about: 'リンについて', f: [['毎朝仕込むスープ', '12時間煮込み'], ['並ばず受け取り', 'NT$1,500以上で配達無料'], ['多言語AI注文', '中・英・日・越・マレー語']], chips: ['看板メニュー', 'ひとりなら何がいい？', '予算300元', 'デリバリー料金は？', 'ベジタリアン向けある？', 'お会計'] },
      vi: { type: 'Món Việt mang đi', tagline: 'Nước dùng của mẹ, ninh 12 tiếng', kicker: 'Quán Việt ở Trung Lịch · Mang đi & giao hàng', title: 'Nước dùng của mẹ,<br>ninh đủ 12 tiếng.', sub: 'Chị Linh ninh xương bò từ sáng sớm mỗi ngày, rau thơm hái trong ngày. Đặt online, đến lấy không phải xếp hàng hoặc giao tận nơi. Trợ lý AI tư vấn bằng tiếng Việt.', prodTitle: 'Thực đơn hôm nay', prodSub: 'Khoảng 15 phút có món. Đến lấy hoặc giao hàng', about: 'Về chị Linh', f: [['Nước dùng ninh mới', 'Ninh 12 tiếng mỗi sáng'], ['Mang đi không chờ', 'Giao miễn phí từ NT$1,500'], ['AI gọi món đa ngôn ngữ', 'Trung · Anh · Nhật · Việt · Mã Lai']], chips: ['Món đặc trưng', 'Ăn một mình gọi gì?', 'Ngân sách 300', 'Phí giao hàng?', 'Có món chay không?', 'Thanh toán'] },
      ms: { type: 'Makanan Vietnam bungkus', tagline: 'Sup ibu, direneh 12 jam', kicker: 'Zhongli tempatan · Bungkus & hantar', title: 'Sup air tangan ibu,<br>direneh 12 jam.', sub: 'Linh merenih sup tulang lembu setiap subuh dengan herba yang dipetik hari itu. Pesan dalam talian, ambil tanpa beratur atau minta dihantar. Pembantu AI menerangkan dalam bahasa anda.', prodTitle: 'Menu hari ini', prodSub: 'Siap dalam kira-kira 15 minit. Ambil sendiri atau hantar', about: 'Tentang Linh', f: [['Sup segar', 'Direneh 12 jam setiap subuh'], ['Tanpa beratur', 'Hantar percuma melebihi NT$1,500'], ['Pesanan AI pelbagai bahasa', 'Cina · EN · Jepun · VI · MS']], chips: ['Hidangan istimewa', 'Makan seorang?', 'Bajet NT$300', 'Kos penghantaran?', 'Ada pilihan vegetarian?', 'Bayar'] },
    },
    products: {
      'ph-beef': { tags: ['hot', 'signature'], kw: ['牛肉', '河粉', '生牛', 'beef', 'pho', 'phở', 'フォー', '牛', 'bò', 'daging'], i18n: { en: ['Rare Beef Pho', '1 bowl', '12-hour beef bone broth with fresh herbs.'], ja: ['牛肉のフォー（レア）', '1杯', '12時間煮込んだ牛骨スープにハーブを添えて。'], vi: ['Phở bò tái', '1 tô', 'Nước dùng xương bò ninh 12 tiếng, kèm rau thơm.'], ms: ['Pho Daging Lembu Separa Masak', '1 mangkuk', 'Sup tulang lembu 12 jam dengan herba segar.'] } },
      'ph-chicken': { tags: ['hot'], kw: ['雞肉', '雞', 'chicken', '鶏', 'gà', 'ayam'], i18n: { en: ['Chicken Pho', '1 bowl', 'Light chicken broth, kids love it.'], ja: ['鶏肉のフォー', '1杯', 'あっさり鶏スープ、お子様にも人気。'], vi: ['Phở gà', '1 tô', 'Nước dùng gà thanh nhẹ, trẻ em rất thích.'], ms: ['Pho Ayam', '1 mangkuk', 'Sup ayam ringan, kegemaran kanak-kanak.'] } },
      'ph-banhmi': { tags: ['value'], kw: ['法國麵包', '麵包', '三明治', 'banh mi', 'bánh mì', 'sandwich', 'バインミー', 'roti'], i18n: { en: ['Bánh Mì', '1 roll', 'Grilled pork, pickled radish and coriander.'], ja: ['バインミー', '1本', '焼き豚、なますとパクチー。'], vi: ['Bánh mì thịt nướng', '1 ổ', 'Thịt heo nướng, đồ chua và ngò.'], ms: ['Bánh Mì', '1 roti', 'Babi panggang, lobak jeruk dan ketumbar.'] } },
      'ph-roll': { tags: ['veg'], kw: ['春捲', '生春捲', '鮮蝦', 'roll', 'spring roll', '生春巻き', 'gỏi cuốn', 'popia', '素'], i18n: { en: ['Fresh Shrimp Rolls ×2', '2 rolls', 'Rice paper rolls with shrimp and greens, peanut dip.'], ja: ['生春巻き 2本', '2本', 'エビと野菜のライスペーパー巻き、ピーナッツソース付き。'], vi: ['Gỏi cuốn tôm ×2', '2 cuốn', 'Bánh tráng cuốn tôm và rau, chấm tương đậu phộng.'], ms: ['Popia Segar Udang ×2', '2 gulung', 'Gulungan kertas beras dengan udang dan sayur, sos kacang.'] } },
      'ph-coffee': { tags: ['hot', 'value'], kw: ['咖啡', '滴漏', '煉乳', 'coffee', 'cà phê', 'コーヒー', 'kopi'], i18n: { en: ['Vietnamese Drip Coffee', '1 cup', 'Condensed milk coffee, iced or hot.'], ja: ['ベトナムコーヒー', '1杯', '練乳入り、アイスまたはホット。'], vi: ['Cà phê phin sữa', '1 ly', 'Cà phê sữa đặc, đá hoặc nóng.'], ms: ['Kopi Titis Vietnam', '1 cawan', 'Kopi susu pekat, sejuk atau panas.'] } },
      'ph-soup': { tags: ['new', 'gift'], kw: ['湯底', '冷凍', '在家', 'broth', 'frozen', 'スープ', 'nước dùng', 'sup'], i18n: { en: ['Frozen Broth Pack', '1 litre', 'Make pho at home, keeps 3 months frozen.'], ja: ['冷凍スープパック', '1リットル', 'おうちでフォーが作れます。冷凍3か月保存。'], vi: ['Gói nước dùng đông lạnh', '1 lít', 'Nấu phở tại nhà, bảo quản đông lạnh 3 tháng.'], ms: ['Pek Sup Beku', '1 liter', 'Masak pho di rumah, tahan 3 bulan beku.'] } },
    },
  },
};
for (const m of MERCHANTS) {
  const x = EXTRA[m.id]; if (!x) continue;
  for (const k of ['cat', 'brand', 'layout', 'ship', 'copy']) if (x[k] !== undefined && m[k] === undefined) m[k] = x[k];
  if (m.products && x.products) for (const p of m.products) { const e = x.products[p.id]; if (e) for (const [k, v] of Object.entries(e)) if (p[k] === undefined) p[k] = v; }
}

// ── 50 種業態：附加 biz/index.js 的業主（略過重複 id），補齊前台需要的欄位 ──
const SHIP_BY_CAT = { service: 'service', food: 'takeout', drink: 'takeout' };
for (const b of BIZ) {
  const m = b && b.merchant;
  if (!m || !m.id || MERCHANTS.some(x => x.id === m.id)) continue;
  const v = (b.theme && b.theme.vars) || {};
  MERCHANTS.push({ layout: 'classic', brand: v.g || v.rose || '#2DB674', ship: { mode: SHIP_BY_CAT[m.cat] || 'ship', fee: 150, free: 1500 }, ...m });
}
for (const m of MERCHANTS) MERCHANT_MAP[m.id] = m;
